In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('resident-population-by-subzone-ethnic-group-and-sex.csv')

In [3]:
by_race = df[(df['level_1'] !=  'Total')&(df['level_2'] ==  'Total')]

#### Within race percentage

In [4]:
race_total = pd.DataFrame(by_race.groupby('level_1')['value'].sum()).reset_index().rename(columns={'value': 'total'})

In [5]:
race_total['perc'] = race_total['total'] / race_total['total'].sum()

In [6]:
by_race1 = pd.merge(by_race, race_total, how='left', on='level_1')

In [7]:
by_race1['perc'] = by_race1['value'] / by_race1['total'] * 100

In [8]:
by_race1.sort_values('perc', ascending=False)

,year,level_1,level_2,level_3,level_4,value,total,perc
409,2015,Malays,Total,Tampines- Total,Tampines East,34020,520960,6.530252
429,2015,Malays,Total,Woodlands- Total,Woodlands East,21560,520960,4.138514
869,2015,Others,Total,Tampines- Total,Tampines East,4360,126820,3.437944
242,2015,Malays,Total,Bedok- Total,Bedok North,17030,520960,3.268965
410,2015,Malays,Total,Tampines- Total,Tampines West,16790,520960,3.222896
197,2015,Chinese,Total,Tampines- Total,Tampines East,89310,2899110,3.080601
360,2015,Malays,Total,Pasir Ris- Total,Pasir Ris Drive,16020,520960,3.075092
638,2015,Indians,Total,Tampines- Total,Tampines East,10800,354860,3.043454
660,2015,Indians,Total,Woodlands- Total,Woodlands East,10730,354860,3.023728
330,2015,Malays,Total,Jurong West- Total,Yunnan,14310,520960,2.746852
541,2015,Indians,Total,Jurong West- Total,Yunnan,7540,354860,2.124782
891,2015,Others,Total,Woodlands- Total,Woodlands East,2660,126820,2.097461
219,2015,Chinese,Total,Woodlands- Total,Woodlands East,60560,2899110,2.088917
11,2015,Chinese,Total,Bedok- Total,Bedok North,59870,2899110,2.065117
683,2015,Others,Total,Bedok- Total,Bedok North,2600,126820,2.050150
326,2015,Malays,Total,Jurong West- Total,Hong Kah,10610,520960,2.036625
440,2015,Malays,Total,Yishun- Total,Yishun West,10520,520960,2.019349
438,2015,Malays,Total,Yishun- Total,Yishun East,10500,520960,2.015510
685,2015,Others,Total,Bedok- Total,Bedok South,2410,126820,1.900331
246,2015,Malays,Total,Bedok- Total,Kaki Bukit,9740,520960,1.869625
426,2015,Malays,Total,Woodlands- Total,Midview,9680,520960,1.858108
198,2015,Chinese,Total,Tampines- Total,Tampines West,53600,2899110,1.848843
808,2015,Others,Total,Pasir Ris- Total,Pasir Ris Drive,2340,126820,1.845135
686,2015,Others,Total,Bedok- Total,Frankel,2310,126820,1.821479
452,2015,Indians,Total,Bedok- Total,Bedok North,6430,354860,1.811982
431,2015,Malays,Total,Woodlands- Total,Woodlands West,9360,520960,1.796683
97,2015,Chinese,Total,Jurong West- Total,Jurong West Central,51820,2899110,1.787445
769,2015,Others,Total,Jurong West- Total,Jurong West Central,2260,126820,1.782053
430,2015,Malays,Total,Woodlands- Total,Woodlands South,9130,520960,1.752534
623,2015,Indians,Total,Sengkang- Total,Rivervale,6060,354860,1.707716
...,...,...,...,...,...,...,...,...
381,2015,Malays,Total,River Valley- Total,One Tree Hill,20,520960,0.003839
371,2015,Malays,Total,Queenstown- Total,Kent Ridge,20,520960,0.003839
349,2015,Malays,Total,Novena- Total,Malcolm,20,520960,0.003839
190,2015,Chinese,Total,Singapore River- Total,Boat Quay,110,2899110,0.003794
194,2015,Chinese,Total,Sungei Kadut- Total,Gali Batu,110,2899110,0.003794
126,2015,Chinese,Total,Orchard- Total,Somerset,90,2899110,0.003104
75,2015,Chinese,Total,Downtown Core- Total,Cecil,90,2899110,0.003104
635,2015,Indians,Total,Sungei Kadut- Total,Gali Batu,10,354860,0.002818
567,2015,Indians,Total,Orchard- Total,Somerset,10,354860,0.002818
604,2015,Indians,Total,River Valley- Total,Paterson,10,354860,0.002818
596,2015,Indians,Total,Queenstown- Total,Port,10,354860,0.002818
592,2015,Indians,Total,Queenstown- Total,National University of S'pore,10,354860,0.002818
575,2015,Indians,Total,Pasir Ris- Total,Loyang West,10,354860,0.002818
554,2015,Indians,Total,Museum- Total,Dhoby Ghaut,10,354860,0.002818
572,2015,Indians,Total,Outram- Total,People's Park,10,354860,0.002818
168,2015,Chinese,Total,Rochor- Total,Mackenzie,80,2899110,0.002759
114,2015,Chinese,Total,Museum- Total,Fort Canning,70,2899110,0.002415
191,2015,Chinese,Total,Singapore River- Total,Clarke Quay,70,2899110,0.002415
166,2015,Chinese,Total,Rochor- Total,Kampong Glam,60,2899110,0.002070
352,2015,Malays,Total,Orchard- Total,Boulevard,10,520960,0.001920
351,2015,Malays,Total,Novena- Total,Mount Pleasant,10,520960,0.001920
344,2015,Malays,Total,Newton- Total,Goodwood Park,10,520960,0.001920
261,2015,Malays,Total,Bukit Merah- Total,Alexandra North,10,520960,0.001920
406,2015,Malays,Total,Singapore River- Total,Robertson Quay,10,520960,0.001920
306,2015,Malays,Total,Downtown Core- Total,Cecil,10,520960,0.001920
345,2015,Malays,Total,Newton- Total,Monk's Hill,10,520960,0.001920
377,2015,Malays,Total,Queenstown- Total,Queensway,10,520960,0.001920
374,2015,Malays,Total,Queenstown- Total,National University of S'pore,10,520960,0.001920
353,2015,Malays,Total,Outram- Total,China Square,10,520960,0.001920
307,2015,Malays,Total,Downtown Core- Total,Central Subzone,10,520960,0.001920

In [9]:
#by_race1.to_csv('by_race.csv', index=False)

#### Within subzone percentage

In [10]:
subzone_total = pd.DataFrame(by_race.groupby('level_4')['value'].sum()).reset_index().rename(columns={'value': 'total'})

In [11]:
by_race2 = pd.merge(by_race, subzone_total, how='left', on='level_4')

In [12]:
by_race2['perc'] = by_race2['value'] / by_race2['total'] * 100

In [13]:
by_race2.sort_values('perc', ascending=False)

,year,level_1,level_2,level_3,level_4,value,total,perc
128,2015,Chinese,Total,Outram- Total,China Square,1540,1600,96.250000
131,2015,Chinese,Total,Outram- Total,People's Park,360,380,94.736842
226,2015,Chinese,Total,Yishun- Total,Springleaf,3560,3880,91.752577
51,2015,Chinese,Total,Bukit Timah- Total,Anak Bukit,20090,21980,91.401274
74,2015,Chinese,Total,Downtown Core- Total,Bugis,2100,2320,90.517241
211,2015,Chinese,Total,Toa Payoh- Total,Sennett,4100,4540,90.308370
184,2015,Chinese,Total,Serangoon- Total,Lorong Chuan,7570,8390,90.226460
214,2015,Chinese,Total,Toa Payoh- Total,Woodleigh,2200,2440,90.163934
73,2015,Chinese,Total,Clementi- Total,West Coast,5290,5890,89.813243
86,2015,Chinese,Total,Hougang- Total,Kovan,22950,25640,89.508580
6,2015,Chinese,Total,Ang Mo Kio- Total,Tagore,7440,8340,89.208633
151,2015,Chinese,Total,Queenstown- Total,National University of S'pore,320,360,88.888889
185,2015,Chinese,Total,Serangoon- Total,Seletar Hills,12040,13580,88.659794
42,2015,Chinese,Total,Bukit Merah- Total,Tiong Bahru,10800,12200,88.524590
8,2015,Chinese,Total,Ang Mo Kio- Total,Yio Chu Kang East,3620,4090,88.508557
4,2015,Chinese,Total,Ang Mo Kio- Total,Sembawang Hills,6080,6900,88.115942
224,2015,Chinese,Total,Yishun- Total,Nee Soon,790,900,87.777778
52,2015,Chinese,Total,Bukit Timah- Total,Coronation Road,5380,6180,87.055016
45,2015,Chinese,Total,Bukit Panjang- Total,Dairy Farm,4660,5380,86.617100
71,2015,Chinese,Total,Clementi- Total,Faber,3750,4330,86.605081
82,2015,Chinese,Total,Hougang- Total,Hougang Central,4180,4830,86.542443
27,2015,Chinese,Total,Bukit Batok- Total,Hillview,15750,18220,86.443469
172,2015,Chinese,Total,Rochor- Total,Victoria,1780,2060,86.407767
189,2015,Chinese,Total,Serangoon- Total,Upper Paya Lebar,13380,15540,86.100386
20,2015,Chinese,Total,Bishan- Total,Upper Thomson,26100,30340,86.025049
206,2015,Chinese,Total,Toa Payoh- Total,Joo Seng,5780,6720,86.011905
90,2015,Chinese,Total,Jurong East- Total,Lakeside,860,1000,86.000000
110,2015,Chinese,Total,Marine Parade- Total,Katong,8270,9620,85.966736
19,2015,Chinese,Total,Bishan- Total,Marymount,27090,31540,85.890932
155,2015,Chinese,Total,Queenstown- Total,Port,120,140,85.714286
...,...,...,...,...,...,...,...,...
381,2015,Malays,Total,River Valley- Total,One Tree Hill,20,1850,1.081081
413,2015,Malays,Total,Tanglin- Total,Nassim,90,8340,1.079137
340,2015,Malays,Total,Marine Parade- Total,Katong,100,9620,1.039501
839,2015,Others,Total,Rochor- Total,Little India,40,3850,1.038961
345,2015,Malays,Total,Newton- Total,Monk's Hill,10,990,1.010101
282,2015,Malays,Total,Bukit Timah- Total,Anak Bukit,220,21980,1.000910
375,2015,Malays,Total,Queenstown- Total,Pasir Panjang 1,40,4010,0.997506
261,2015,Malays,Total,Bukit Merah- Total,Alexandra North,10,1010,0.990099
389,2015,Malays,Total,Rochor- Total,Victoria,20,2060,0.970874
350,2015,Malays,Total,Novena- Total,Moulmein,80,8480,0.943396
302,2015,Malays,Total,Clementi- Total,Faber,40,4330,0.923788
379,2015,Malays,Total,River Valley- Total,Institution Hill,30,3380,0.887574
412,2015,Malays,Total,Tanglin- Total,Chatsworth,50,5740,0.871080
305,2015,Malays,Total,Downtown Core- Total,Bugis,20,2320,0.862069
237,2015,Malays,Total,Ang Mo Kio- Total,Tagore,70,8340,0.839329
425,2015,Malays,Total,Toa Payoh- Total,Woodleigh,20,2440,0.819672
342,2015,Malays,Total,Marine Parade- Total,Mountbatten,80,10210,0.783546
386,2015,Malays,Total,Rochor- Total,Little India,30,3850,0.779221
286,2015,Malays,Total,Bukit Timah- Total,Holland Road,80,10280,0.778210
436,2015,Malays,Total,Yishun- Total,Springleaf,30,3880,0.773196
349,2015,Malays,Total,Novena- Total,Malcolm,20,2630,0.760456
285,2015,Malays,Total,Bukit Timah- Total,Hillcrest,60,8820,0.680272
304,2015,Malays,Total,Clementi- Total,West Coast,40,5890,0.679117
289,2015,Malays,Total,Bukit Timah- Total,Ulu Pandan,70,10730,0.652377
353,2015,Malays,Total,Outram- Total,China Square,10,1600,0.625000
343,2015,Malays,Total,Newton- Total,Cairnhill,20,3330,0.600601
400,2015,Malays,Total,Serangoon- Total,Lorong Chuan,50,8390,0.595948
348,2015,Malays,Total,Novena- Total,Dunearn,20,3910,0.511509
283,2015,Malays,Total,Bukit Timah- Total,Coronation Road,30,6180,0.485437
406,2015,Malays,Total,Singapore River- Total,Robertson Quay,10,2410,0.414938

In [14]:
by_race2[by_race2['level_4'] == 'Mackenzie']

     year  level_1 level_2        level_3    level_4  value  total       perc
168  2015  Chinese   Total  Rochor- Total  Mackenzie     80    110  72.727273
609  2015  Indians   Total  Rochor- Total  Mackenzie     20    110  18.181818
840  2015   Others   Total  Rochor- Total  Mackenzie     10    110   9.090909

In [15]:
by_race2[by_race2['level_4'] == 'Western Water Catchment']

,year,level_1,level_2,level_3,level_4,value,total,perc
215,2015,Chinese,Total,Western Water Catchment- Total,Western Water Catchment,730,890,82.022472
656,2015,Indians,Total,Western Water Catchment- Total,Western Water Catchment,90,890,10.112360
887,2015,Others,Total,Western Water Catchment- Total,Western Water Catchment,70,890,7.865169

In [16]:
by_race[by_race['level_4'] == 'Mackenzie']

      year  level_1 level_2        level_3    level_4  value
911   2015  Chinese   Total  Rochor- Total  Mackenzie     80
2218  2015  Indians   Total  Rochor- Total  Mackenzie     20
2906  2015   Others   Total  Rochor- Total  Mackenzie     10

In [17]:
len(by_race['level_4'].unique())

231

In [18]:
subzone_perc = pd.DataFrame(by_race2.groupby(['level_4', 'level_1'], sort=True)['perc'].sum())\
    .reset_index().sort_values(['level_4', 'perc'], ascending=False)
overall_perc = pd.DataFrame(by_race.groupby('level_1')['value'].sum() / by_race['value'].sum() * 100).reset_index()
subzone_perc = pd.merge(subzone_perc, overall_perc, on='level_1', how='left')
subzone_perc['diff'] = subzone_perc['perc'] - subzone_perc['value']

In [19]:
#subzone_perc.to_csv('subzone_perc.csv', index=False)

In [20]:
subzone_perc.sort_values('diff', ascending=False)

             level_4  level_1       perc      value       diff
656     Fort Canning   Others  37.500000   3.250336  34.249664
231          Sentosa   Others  33.783784   3.250336  30.533447
556     Kampong Glam  Indians  38.888889   9.094893  29.793996
383    Newton Circus   Others  30.434783   3.250336  27.184446
162          Tanglin   Others  28.205128   3.250336  24.954792
837        Boat Quay   Others  27.777778   3.250336  24.527441
369        One North   Others  27.419355   3.250336  24.169018
777  Central Subzone   Others  25.531915   3.250336  22.281579
756     China Square  Chinese  96.250000  74.302813  21.947187
155    Tanjong Pagar   Others  25.000000   3.250336  21.749664
781            Cecil   Others  25.000000   3.250336  21.749664
738      Clarke Quay   Others  25.000000   3.250336  21.749664
271          Seletar   Others  24.000000   3.250336  20.749664
695      Dhoby Ghaut   Others  23.809524   3.250336  20.559187
314    People's Park  Chinese  94.736842  74.302813  20.434029
361     Orange Grove   Others  23.611111   3.250336  20.360775
667      Farrer Park  Indians  29.073482   9.094893  19.978589
201         Somerset   Others  23.076923   3.250336  19.826587
281   Robertson Quay   Others  21.991701   3.250336  18.741365
821        Boulevard   Others  21.951220   3.250336  18.700883
151      Tanjong Rhu  Indians  27.232538   9.094893  18.137644
196       Springleaf  Chinese  91.752577  74.302813  17.449764
883       Anak Bukit  Chinese  91.401274  74.302813  17.098461
812            Bugis  Chinese  90.517241  74.302813  16.214429
489     Little India  Indians  25.194805   9.094893  16.099912
234          Sennett  Chinese  90.308370  74.302813  16.005557
769      Changi West   Malays  29.310345  13.351957  15.958387
476     Lorong Chuan  Chinese  90.226460  74.302813  15.923647
274          Selegie  Indians  25.000000   9.094893  15.905107
44         Woodleigh  Chinese  90.163934  74.302813  15.861122
..               ...      ...        ...        ...        ...
607     Holland Road   Malays   0.778210  13.351957 -12.573747
199       Springleaf   Malays   0.773196  13.351957 -12.578762
456          Malcolm   Malays   0.760456  13.351957 -12.591501
492      Leonie Hill  Chinese  61.632653  74.302813 -12.670160
619        Hillcrest   Malays   0.680272  13.351957 -12.671685
70        West Coast   Malays   0.679117  13.351957 -12.672840
94        Ulu Pandan   Malays   0.652377  13.351957 -12.699581
759     China Square   Malays   0.625000  13.351957 -12.726957
787        Cairnhill   Malays   0.600601  13.351957 -12.751357
479     Lorong Chuan   Malays   0.595948  13.351957 -12.756010
154    Tanjong Pagar  Chinese  61.538462  74.302813 -12.764351
161          Tanglin  Chinese  61.538462  74.302813 -12.764351
689          Dunearn   Malays   0.511509  13.351957 -12.840449
712  Coronation Road   Malays   0.485437  13.351957 -12.866521
283   Robertson Quay   Malays   0.414938  13.351957 -12.937020
150      Tanjong Rhu  Chinese  61.273210  74.302813 -13.029603
836        Boat Quay  Chinese  61.111111  74.302813 -13.191702
340  Pasir Ris Drive  Chinese  60.726295  74.302813 -13.576518
52   Woodlands South  Chinese  60.591683  74.302813 -13.711130
421          Midview  Chinese  59.487613  74.302813 -14.815200
48    Woodlands West  Chinese  58.693009  74.302813 -15.609804
737      Clarke Quay  Chinese  58.333333  74.302813 -15.969480
382    Newton Circus  Chinese  56.521739  74.302813 -17.781074
780            Cecil  Chinese  56.250000  74.302813 -18.052813
378      North Coast  Chinese  55.715264  74.302813 -18.587549
230          Sentosa  Chinese  54.729730  74.302813 -19.573083
772     Changi Point  Chinese  53.750000  74.302813 -20.552813
768      Changi West  Chinese  44.252874  74.302813 -30.049939
655     Fort Canning  Chinese  43.750000  74.302813 -30.552813
557     Kampong Glam  Chinese  33.333333  74.302813 -40.969480

[903 rows x 5 columns]

In [21]:
subzone_perc[subzone_perc['level_1'] == 'Others'].sort_values('diff', ascending=False)

                 level_4 level_1       perc     value       diff
656         Fort Canning  Others  37.500000  3.250336  34.249664
231              Sentosa  Others  33.783784  3.250336  30.533447
383        Newton Circus  Others  30.434783  3.250336  27.184446
162              Tanglin  Others  28.205128  3.250336  24.954792
837            Boat Quay  Others  27.777778  3.250336  24.527441
369            One North  Others  27.419355  3.250336  24.169018
777      Central Subzone  Others  25.531915  3.250336  22.281579
781                Cecil  Others  25.000000  3.250336  21.749664
155        Tanjong Pagar  Others  25.000000  3.250336  21.749664
738          Clarke Quay  Others  25.000000  3.250336  21.749664
271              Seletar  Others  24.000000  3.250336  20.749664
695          Dhoby Ghaut  Others  23.809524  3.250336  20.559187
361         Orange Grove  Others  23.611111  3.250336  20.360775
201             Somerset  Others  23.076923  3.250336  19.826587
281       Robertson Quay  Others  21.991701  3.250336  18.741365
821            Boulevard  Others  21.951220  3.250336  18.700883
330             Paterson  Others  18.750000  3.250336  15.499664
365        One Tree Hill  Others  18.378378  3.250336  15.128042
438      Maritime Square  Others  17.968750  3.250336  14.718414
522           Kent Ridge  Others  17.592593  3.250336  14.342256
410          Mount Emily  Others  17.117117  3.250336  13.866781
494          Leonie Hill  Others  16.734694  3.250336  13.484357
785            Cairnhill  Others  15.915916  3.250336  12.665580
289               Ridout  Others  15.714286  3.250336  12.463949
96              Tyersall  Others  15.625000  3.250336  12.374664
765           Chatsworth  Others  15.156794  3.250336  11.906458
418          Monk's Hill  Others  15.151515  3.250336  11.901179
497          Leedon Park  Others  14.992026  3.250336  11.741689
629        Goodwood Park  Others  14.285714  3.250336  11.035378
296            Queensway  Others  14.285714  3.250336  11.035378
..                   ...     ...        ...       ...        ...
898       Alexandra Hill  Others   2.044728  3.250336  -1.205608
51        Woodlands West  Others   2.036474  3.250336  -1.213862
763            Cheng San  Others   2.014775  3.250336  -1.235561
551  Kampong Tiong Bahru  Others   2.005731  3.250336  -1.244606
27        Yishun Central  Others   2.000000  3.250336  -1.250336
236              Sennett  Others   1.982379  3.250336  -1.267958
799     Bukit Batok West  Others   1.974984  3.250336  -1.275353
279              Saujana  Others   1.958480  3.250336  -1.291856
145            Teck Whye  Others   1.923077  3.250336  -1.327259
827            Boon Teck  Others   1.917989  3.250336  -1.332347
669          Farrer Park  Others   1.916933  3.250336  -1.333403
381          North Coast  Others   1.916496  3.250336  -1.333841
78         Waterway East  Others   1.905434  3.250336  -1.344902
179             Tai Seng  Others   1.903467  3.250336  -1.346869
310         Potong Pasir  Others   1.895735  3.250336  -1.354602
587         Hougang West  Others   1.875499  3.250336  -1.374838
757         China Square  Others   1.875000  3.250336  -1.375336
483        Lorong Ah Soo  Others   1.842644  3.250336  -1.407692
149        Teban Gardens  Others   1.833421  3.250336  -1.416916
591         Hougang East  Others   1.778386  3.250336  -1.471951
846            Bendemeer  Others   1.773574  3.250336  -1.476763
814                Bugis  Others   1.724138  3.250336  -1.526198
791          Bukit Merah  Others   1.694915  3.250336  -1.555421
716          Compassvale  Others   1.673866  3.250336  -1.576470
195          Sungei Road  Others   1.652893  3.250336  -1.597444
3                 Yunnan  Others   1.636338  3.250336  -1.613998
647        Geylang Bahru  Others   1.632970  3.250336  -1.617366
870              Bangkit  Others   1.597310  3.250336  -1.653027
595      Hougang Central  Others   1.449275  3.250336  -1.801061
490         Little India  Others   1.038961  3.250336  -2.211375

[231 rows x 5 columns]

In [22]:
subzone_perc[subzone_perc['level_1'] == 'Chinese'].sort_values('diff', ascending=False)

                           level_4  level_1       perc      value       diff
756                   China Square  Chinese  96.250000  74.302813  21.947187
314                  People's Park  Chinese  94.736842  74.302813  20.434029
196                     Springleaf  Chinese  91.752577  74.302813  17.449764
883                     Anak Bukit  Chinese  91.401274  74.302813  17.098461
812                          Bugis  Chinese  90.517241  74.302813  16.214429
234                        Sennett  Chinese  90.308370  74.302813  16.005557
476                   Lorong Chuan  Chinese  90.226460  74.302813  15.923647
44                       Woodleigh  Chinese  90.163934  74.302813  15.861122
67                      West Coast  Chinese  89.813243  74.302813  15.510430
508                          Kovan  Chinese  89.508580  74.302813  15.205768
180                         Tagore  Chinese  89.208633  74.302813  14.905820
393  National University of S'pore  Chinese  88.888889  74.302813  14.586076
266                  Seletar Hills  Chinese  88.659794  74.302813  14.356981
126                    Tiong Bahru  Chinese  88.524590  74.302813  14.221777
32               Yio Chu Kang East  Chinese  88.508557  74.302813  14.205745
258                Sembawang Hills  Chinese  88.115942  74.302813  13.813129
385                       Nee Soon  Chinese  87.777778  74.302813  13.474965
709                Coronation Road  Chinese  87.055016  74.302813  12.752203
701                     Dairy Farm  Chinese  86.617100  74.302813  12.314288
678                          Faber  Chinese  86.605081  74.302813  12.302268
592                Hougang Central  Chinese  86.542443  74.302813  12.239630
612                       Hillview  Chinese  86.443469  74.302813  12.140656
79                        Victoria  Chinese  86.407767  74.302813  12.104954
87                Upper Paya Lebar  Chinese  86.100386  74.302813  11.797573
83                   Upper Thomson  Chinese  86.025049  74.302813  11.722237
572                       Joo Seng  Chinese  86.011905  74.302813  11.709092
504                       Lakeside  Chinese  86.000000  74.302813  11.697187
536                         Katong  Chinese  85.966736  74.302813  11.663923
433                      Marymount  Chinese  85.890932  74.302813  11.588119
311                           Port  Chinese  85.714286  74.302813  11.411473
..                             ...      ...        ...        ...        ...
168                  Tampines East  Chinese  64.488411  74.302813  -9.814402
142                      Teck Whye  Chinese  64.423077  74.302813  -9.879736
273                        Selegie  Chinese  64.285714  74.302813 -10.017099
564                     Kaki Bukit  Chinese  64.135228  74.302813 -10.167585
270                        Seletar  Chinese  64.000000  74.302813 -10.302813
804               Bukit Batok East  Chinese  63.991770  74.302813 -10.311043
828                 Boon Lay Place  Chinese  63.966570  74.302813 -10.336243
776                Central Subzone  Chinese  63.829787  74.302813 -10.473026
60                       Woodgrove  Chinese  63.803681  74.302813 -10.499132
56                  Woodlands East  Chinese  63.406973  74.302813 -10.895840
520                     Kent Ridge  Chinese  62.037037  74.302813 -12.265776
146                  Teban Gardens  Chinese  61.864851  74.302813 -12.437962
492                    Leonie Hill  Chinese  61.632653  74.302813 -12.670160
161                        Tanglin  Chinese  61.538462  74.302813 -12.764351
154                  Tanjong Pagar  Chinese  61.538462  74.302813 -12.764351
150                    Tanjong Rhu  Chinese  61.273210  74.302813 -13.029603
836                      Boat Quay  Chinese  61.111111  74.302813 -13.191702
340                Pasir Ris Drive  Chinese  60.726295  74.302813 -13.576518
52                 Woodlands South  Chinese  60.591683  74.302813 -13.711130
421                        Midview  Chinese  59.487613  74.302813 -14.815200
48                  Woodlands West  Chinese  58.693009  74.302813 -15.609804
737                    Clarke Quay  Chinese  58.333333  74.302813 -15.969480
382                  Newton Circus  Chinese  56.521739  74.302813 -17.781074
780                          Cecil  Chinese  56.250000  74.302813 -18.052813
378                    North Coast  Chinese  55.715264  74.302813 -18.587549
230                        Sentosa  Chinese  54.729730  74.302813 -19.573083
772                   Changi Point  Chinese  53.750000  74.302813 -20.552813
768                    Changi West  Chinese  44.252874  74.302813 -30.049939
655                   Fort Canning  Chinese  43.750000  74.302813 -30.552813
557                   Kampong Glam  Chinese  33.333333  74.302813 -40.969480

[231 rows x 5 columns]

In [23]:
subzone_perc[subzone_perc['level_1'] == 'Malays'].sort_values('diff', ascending=False)

              level_4 level_1       perc      value       diff
769       Changi West  Malays  29.310345  13.351957  15.958387
379       North Coast  Malays  29.021218  13.351957  15.669261
49     Woodlands West  Malays  28.449848  13.351957  15.097891
422           Midview  Malays  27.252252  13.351957  13.900295
341   Pasir Ris Drive  Malays  26.933423  13.351957  13.581466
773      Changi Point  Malays  26.250000  13.351957  12.898043
53    Woodlands South  Malays  25.481440  13.351957  12.129483
147     Teban Gardens  Malays  25.144054  13.351957  11.792097
169     Tampines East  Malays  24.564951  13.351957  11.212993
565        Kaki Bukit  Malays  23.860853  13.351957  10.508895
829    Boon Lay Place  Malays  23.850852  13.351957  10.498894
143         Teck Whye  Malays  23.483728  13.351957  10.131770
61          Woodgrove  Malays  23.257111  13.351957   9.905154
57     Woodlands East  Malays  22.573553  13.351957   9.221595
597    Hong Kah North  Malays  22.343805  13.351957   8.991848
545       Kampong Ubi  Malays  21.650265  13.351957   8.298307
165     Tampines West  Malays  21.495327  13.351957   8.143370
805  Bukit Batok East  Malays  21.399177  13.351957   8.047219
675             Fajar  Malays  20.358610  13.351957   7.006653
1              Yunnan  Malays  20.186204  13.351957   6.834247
375         Northland  Malays  19.842053  13.351957   6.490096
860       Bedok North  Malays  19.818457  13.351957   6.466499
333    Pasir Ris West  Malays  19.515552  13.351957   6.163594
21        Yishun East  Malays  19.136140  13.351957   5.784183
318        Peng Siang  Malays  18.674136  13.351957   5.322179
601          Hong Kah  Malays  18.659866  13.351957   5.307909
13        Yishun West  Malays  18.172396  13.351957   4.820438
277           Saujana  Malays  17.822170  13.351957   4.470213
706          Crawford  Malays  17.659138  13.351957   4.307180
868           Bangkit  Malays  17.444304  13.351957   4.092347
..                ...     ...        ...        ...        ...
631     Goodwood Park  Malays   1.098901  13.351957 -12.253056
367     One Tree Hill  Malays   1.081081  13.351957 -12.270876
400            Nassim  Malays   1.079137  13.351957 -12.272821
539            Katong  Malays   1.039501  13.351957 -12.312456
420       Monk's Hill  Malays   1.010101  13.351957 -12.341856
886        Anak Bukit  Malays   1.000910  13.351957 -12.351048
355   Pasir Panjang 1  Malays   0.997506  13.351957 -12.354451
894   Alexandra North  Malays   0.990099  13.351957 -12.361858
82           Victoria  Malays   0.970874  13.351957 -12.381084
416          Moulmein  Malays   0.943396  13.351957 -12.408561
681             Faber  Malays   0.923788  13.351957 -12.428170
583  Institution Hill  Malays   0.887574  13.351957 -12.464383
767        Chatsworth  Malays   0.871080  13.351957 -12.480877
815             Bugis  Malays   0.862069  13.351957 -12.489888
183            Tagore  Malays   0.839329  13.351957 -12.512629
47          Woodleigh  Malays   0.819672  13.351957 -12.532285
404       Mountbatten  Malays   0.783546  13.351957 -12.568412
491      Little India  Malays   0.779221  13.351957 -12.572737
607      Holland Road  Malays   0.778210  13.351957 -12.573747
199        Springleaf  Malays   0.773196  13.351957 -12.578762
456           Malcolm  Malays   0.760456  13.351957 -12.591501
619         Hillcrest  Malays   0.680272  13.351957 -12.671685
70         West Coast  Malays   0.679117  13.351957 -12.672840
94         Ulu Pandan  Malays   0.652377  13.351957 -12.699581
759      China Square  Malays   0.625000  13.351957 -12.726957
787         Cairnhill  Malays   0.600601  13.351957 -12.751357
479      Lorong Chuan  Malays   0.595948  13.351957 -12.756010
689           Dunearn  Malays   0.511509  13.351957 -12.840449
712   Coronation Road  Malays   0.485437  13.351957 -12.866521
283    Robertson Quay  Malays   0.414938  13.351957 -12.937020

[210 rows x 5 columns]

In [24]:
subzone_perc[subzone_perc['level_1'] == 'Indians'].sort_values('diff', ascending=False)

                           level_4  level_1       perc     value       diff
556                   Kampong Glam  Indians  38.888889  9.094893  29.793996
667                    Farrer Park  Indians  29.073482  9.094893  19.978589
151                    Tanjong Rhu  Indians  27.232538  9.094893  18.137644
489                   Little India  Indians  25.194805  9.094893  16.099912
274                        Selegie  Indians  25.000000  9.094893  15.905107
402                    Mountbatten  Indians  23.702253  9.094893  14.607359
770                    Changi West  Indians  22.988506  9.094893  13.893612
848                      Bencoolen  Indians  20.547945  9.094893  11.453052
211                         Siglap  Indians  20.461095  9.094893  11.366202
493                    Leonie Hill  Indians  20.408163  9.094893  11.313270
657                   Fort Canning  Indians  18.750000  9.094893   9.655107
204          Singapore Polytechnic  Indians  18.750000  9.094893   9.655107
521                     Kent Ridge  Indians  18.518519  9.094893   9.423625
864                       Bayshore  Indians  18.181818  9.094893   9.086925
462                      Mackenzie  Indians  18.181818  9.094893   9.086925
501                       Lavender  Indians  17.231365  9.094893   8.136472
739                    Clarke Quay  Indians  16.666667  9.094893   7.571773
766                     Chatsworth  Indians  14.982578  9.094893   5.887685
553                   Kampong Java  Indians  14.920071  9.094893   5.825178
194                    Sungei Road  Indians  14.462810  9.094893   5.367917
581               Institution Hill  Indians  14.201183  9.094893   5.106290
247              Sembawang Straits  Indians  14.117647  9.094893   5.022754
892                Alexandra North  Indians  13.861386  9.094893   4.766493
100                      Turf Club  Indians  13.636364  9.094893   4.541470
156                  Tanjong Pagar  Indians  13.461538  9.094893   4.366645
380                    North Coast  Indians  13.347023  9.094893   4.252129
384                  Newton Circus  Indians  13.043478  9.094893   3.948585
844                      Bendemeer  Indians  12.976648  9.094893   3.881755
73                           Wenya  Indians  12.761021  9.094893   3.666128
782                          Cecil  Indians  12.500000  9.094893   3.405107
..                             ...      ...        ...       ...        ...
869                        Bangkit  Indians   6.305170  9.094893  -2.789723
331                       Paterson  Indians   6.250000  9.094893  -2.844893
618                      Hillcrest  Indians   6.235828  9.094893  -2.859066
190                     Sunset Way  Indians   6.200318  9.094893  -2.894575
323                       Pei Chun  Indians   6.196944  9.094893  -2.897949
235                        Sennett  Indians   6.167401  9.094893  -2.927492
354                Pasir Panjang 1  Indians   5.985037  9.094893  -3.109856
509                          Kovan  Indians   5.811232  9.094893  -3.283661
93                      Ulu Pandan  Indians   5.591799  9.094893  -3.503095
715                    Compassvale  Indians   5.561555  9.094893  -3.533338
386                       Nee Soon  Indians   5.555556  9.094893  -3.539338
186                     Swiss Club  Indians   5.405405  9.094893  -3.689488
610                  Holland Drive  Indians   5.344585  9.094893  -3.750308
455                        Malcolm  Indians   5.323194  9.094893  -3.771699
68                      West Coast  Indians   5.093379  9.094893  -4.001515
358                          Oxley  Indians   5.072464  9.094893  -4.022430
477                   Lorong Chuan  Indians   5.005959  9.094893  -4.088934
466                    Loyang West  Indians   5.000000  9.094893  -4.094893
45                       Woodleigh  Indians   4.918033  9.094893  -4.176861
672                   Farrer Court  Indians   4.914530  9.094893  -4.180363
197                     Springleaf  Indians   4.896907  9.094893  -4.197986
822                      Boulevard  Indians   4.878049  9.094893  -4.216845
696                    Dhoby Ghaut  Indians   4.761905  9.094893  -4.332989
301            Punggol Town Centre  Indians   4.729730  9.094893  -4.365164
711                Coronation Road  Indians   4.692557  9.094893  -4.402337
606                   Holland Road  Indians   4.280156  9.094893  -4.814738
884                     Anak Bukit  Indians   3.821656  9.094893  -5.273237
395  National University of S'pore  Indians   2.777778  9.094893  -6.317116
315                  People's Park  Indians   2.631579  9.094893  -6.463314
758                   China Square  Indians   1.250000  9.094893  -7.844893

[231 rows x 5 columns]

In [25]:
contour = pd.DataFrame()
for i in [4,3,2,1]:
    t1 = subzone_perc[(subzone_perc['diff'] >= -i) & (subzone_perc['diff'] < -(i-1))]
    t1['diff_perc'] = i
    t2 = subzone_perc[(subzone_perc['diff'] > (i-1)) & (subzone_perc['diff'] <= i)]
    t2['diff_perc'] = i
    contour = pd.concat([contour, t1, t2])

/Users/dianaow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/dianaow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [38]:
contour = pd.DataFrame()
for i in [4,3,2,1]:
    t1 = subzone_perc[(subzone_perc['diff'] >= -i) & (subzone_perc['diff'] < i)]
    t1['diff_perc'] = i
    contour = pd.concat([contour, t1])

/Users/dianaow/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [45]:
# Diverse subzones (high representation across all ethnic groups)
test1 = pd.DataFrame(contour[contour['diff_perc'] == 3].groupby('level_4')['diff'].count()).reset_index()
f = test1[test1['diff'] == 4]
len(f)

31

In [43]:
len(subzone_perc['level_4'].unique())

231

#### Within planning area percentage

In [ ]:
PA_perc = pd.DataFrame(by_race2.groupby(['level_3', 'level_1'], sort=True)['value'].sum())\
    .reset_index().sort_values(['level_3', 'perc'], ascending=False)
PA_perc = pd.merge(PA_perc, overall_perc, on='level_1', how='left')
PA_perc['diff'] = PA_perc['perc'] - subzone_perc['value']

In [ ]:
overall_perc